// SPDX-License-Identifier: Apache-2.0
// Shared helpers (part b) for client.test.ts sub-modules.
// Extracted from client.test.ts during modularization.
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { DecisionEngineClient, DecisionEngineError, ServerError } from "./client.js";
import { HOSTNAME_HASH_HEADER } from "./client_device_headers.js";
import { clearHostedDeviceBindingTokenCacheForTests } from "./client_device_binding.js";
import { expectManifestBackedIntegrationsEqual } from "./test_contract_helpers.js";
import {
  ALGENTA_OWNED_HOSTS,
  ALGENTA_OWNED_SUFFIXES,
  API_KEY_PREFIX_LIVE,
  API_KEY_PREFIX_TEST,
  AUTH_SCHEME,
  BRAND,
  CONTRACT_VERSION,
  DEFAULT_BASE_URL,
  DEPRECATION_WINDOW_DAYS,
  INTEGRATIONS,
  LEGACY_DOMAINS,
  LEGACY_ENV_VARS,
  LEGACY_HEADERS,
  MCP_ENDPOINT,
  MCP_TOOLS_ENDPOINT,
  PLAN_LIMITS,
  PRIVATE_HOST_SUFFIXES,
  PRIMARY_DATA_QUERY_CONTRACT,
  READ_ONLY_DEFAULT,
  VENDOR_TELEMETRY_HOSTS,
  WRITE_CONFIRMATION_REQUIRED,
} from "./contract.js";
import type {
  RuntimeBenchmarkBaseline,
  RuntimeBenchmarkClassCode,
  RuntimeBenchmarkDiscoveryRule,
  RuntimeBenchmarkMetric,
  RuntimeEvaluationDimension,
  RuntimeEvaluationMethod,
  RuntimeExecutionStateField,
  RuntimeExecutionValidityRule,
  RuntimeExternalNondeterminismSource,
  RuntimeFailureCode,
  RuntimeInvariantName,
  RuntimeArtifactLineageStep,
  RuntimeAdminEndpoint,
  RuntimeCapabilityField,
  RuntimeCapabilityRule,
  RuntimeLineageNodeField,
  RuntimeNondeterminismArtifact,
  RuntimeMemoryRegion,
  RuntimeMemoryRule,
  RuntimeModuleId,
  RuntimeNonShippingRule,
  RuntimeProofObligation,
  RuntimePublicEndpoint,
  RuntimeReleaseArtifact,
  RuntimeReleaseBlocker,
  RuntimeReleaseGateId,
  RuntimeSLOBudgetAppliesTo,
  RuntimeSchedulerInvariant,
  RuntimeSchedulerMaximizeObjective,
  RuntimeSchedulerMinimizeObjective,
  RuntimeSLOBudgetName,
  RuntimeSchedulerPolicy,
  RuntimeFeatureFlagEndpoint,
  RuntimeThreatClass,
  RuntimeThreatControl,
  RuntimeThreatRule,
} from "./types.js";
import {
  SHIPPING_BENCHMARK_DISCOVERY_RULE,
  NON_SHIPPING_RULE,
  DECISION_WORKFLOW_BENCHMARK_EVIDENCE,
  makeDiscoveredSourceInventory,
  makeBenchmarkDiscoveryLanePayload,
  makeKernelPromotionCriteriaPayload,
  makeQueryResponse,
  makeLLMModelsPayload,
  makeDecisionPlanPayload,
  makeProductDecisionPayload,
  makeProductAgentRunPayload,
  makeProductOptimizePayload,
  makeProductRetrievePayload,
  makeProductForecastPayload,
  makeDecisionLogPayload,
  makeDecisionListPayload,
  makeExecutionReceiptPayload,
  makeDecisionEnvelopePayload,
  makeRecommendPayload,
  makeScorePayload,
  makeComparePayload,
  makeAgentRunPayload,
  makeAgentRunEventsPayload,
  makeAgentRunListPayload,
  makeAgentRunCheckpointsPayload,
  makeAgentRunMissionEventsPayload,
  makeAgentRunMissionEventQueryPayload,
  makeAgentRunCheckpointQueryPayload,
  makeAgentRunReplayPayload,
  makeAgentRunTelemetryPayload,
  makeAgentRunTelemetryQueryPayload,
  cloneJsonValue,
  makeContractPayload,
} from "./_client_test_helpers.js";

export function makeRuntimeManifestPayload(): Record<string, unknown> {
  return {
    runtime_version: "2026.05.0",
    mojo_version: "25.4.0",
    llm_core_manifest: "llm-core-v1",
    module_manifest_version: "runtime-manifest-v1",
    generated_at: "2026-05-22T12:00:00Z",
    modules: [
      {
        name: "bpe_tokenizer",
        capability_id: "mojo_llm_runtime_core.bpe_tokenizer",
        owner: "algenta-runtime-core",
        contract_boundary: "Deterministic Mojo kernel with a bounded manifest-listed surface.",
        function_count: 2,
        functions: ["encode", "decode"],
        layer: "mojo_llm_runtime_core",
        maturity: "channel_covered",
        public_supported_channels: ["python_sdk", "typescript_sdk", "cli", "mcp"],
        validated_auxiliary_channels: ["bundled_worker", "runtime_local"],
        feature_flag_channels: ["http_api_feature_flag"],
        proof_obligations: ["numerical parity"],
        proof_artifacts: ["build/proof.json"],
        promotion_status: "shipping",
        rollback_flag: "runtime.manifest.module.bpe_tokenizer.rollback_to_python",
        benchmark_report_ref: "build/bench.json",
        parity_report_ref: "build/llm_rollout_parity_benchmark.json",
        schema_compat_report_ref: "tests/test_runtime_schema_surface.py",
        isolation_proof_ref: "tests/test_runtime_manifest.py",
        replay_proof_ref: "tests/test_runtime_release_validation.py",
        benchmark_artifact: "build/bench.json",
        benchmark_speedup_x: 101.0,
        compiled_artifact: "mojo_build/bpe_tokenizer",
        compiled_engine: "mojo",
        max_cold_ms: 12.0,
        max_warm_ms: 4.0,
        max_hot_ms: 2.0,
      },
    ],
    compiled_artifacts: [
      {
        kind: "compiled_mojo_binary",
        path: "mojo_build/bpe_tokenizer",
        sha256: "e".repeat(64),
        size_bytes: 4096,
      },
    ],
    supported_channels: ["python_sdk", "typescript_sdk", "cli", "mcp"],
    validated_auxiliary_channels: ["bundled_worker", "runtime_local"],
    feature_flag_channels: ["http_api_feature_flag"],
    maturity: { bpe_tokenizer: "channel_covered" },
    policy_snapshot: {
      snapshot_id: "policy-v1",
      sha256: "a".repeat(64),
      source: "governance/policies/current.json",
      description: "Signed policy snapshot",
    },
    schema_snapshot: {
      snapshot_id: "schema-v1",
      sha256: "b".repeat(64),
      source: "schemas/runtime/current.json",
      description: "Signed schema snapshot",
    },
    deployment_mode: "local_dev_daemon",
    deployment_modes: {
      current: "local_dev_daemon",
      supported_modes: [
        "saas",
        "vpc",
        "self_hosted",
        "air_gapped",
        "hybrid_provider",
        "local_dev_daemon",
      ],
      rule: "Deployment mode availability is defined by the signed runtime manifest only.",
    },
    shipping_contract: {
      module_count: 1,
      function_count: 2,
      runtime_core_layer: "mojo_llm_runtime_core",
      benchmark_discovery_rule: SHIPPING_BENCHMARK_DISCOVERY_RULE,
    },
    benchmark_discovery_lane: makeBenchmarkDiscoveryLanePayload(),
    advertised_capabilities: {
      runtime_modules: ["bpe_tokenizer"],
      public_endpoints: ["/v1/meta/contract"],
      admin_endpoints: ["/v1/admin/runtime/modules"],
      feature_flag_endpoints: ["/v1/libraries"],
    },
    system_invariants: [
      { name: "Manifest Truth", statement: "No capability is advertised unless it appears in the signed runtime manifest." },
    ],
    execution_model: {
      state_fields: ["request"],
      allowed_transitions: ["model_call_started"],
      validity_rules: ["schema-valid"],
    },
    external_nondeterminism: {
      sources: ["provider responses"],
      rule: "Every nondeterministic dependency must be captured as a replay artifact reference.",
      required_artifacts: ["provider response record"],
      failure_codes: ["replay_mismatch"],
    },
    artifact_lineage: {
      artifact_flow: ["input"],
      required_node_fields: ["node_id"],
      immutability_rule: "Every lineage node is immutable and content-addressed.",
    },
    capability_algebra: {
      required_fields: ["tool_name"],
      enums: {
        side_effect_class: ["read_only", "write_scoped", "write_external", "exec_external", "network_external"],
        risk_level: ["low", "medium", "high", "critical"],
        replayability: ["deterministic", "artifact_backed", "non_replayable"],
      },
      rules: ["MCP tools are untrusted by default."],
    },
    kernel_promotion_criteria: makeKernelPromotionCriteriaPayload(),
    proof_matrix: [
      {
        layer: "mojo_llm_runtime_core",
        status: "channel_covered",
        obligations: ["numerical parity"],
        evidence_paths: ["build/proof.json"],
      },
    ],
    benchmarking: {
      classes: [
        {
          code: "B1",
          description: "microkernel latency",
          evidence_paths: ["benchmarks/summary.json"],
        },
        {
          code: "B8",
          description: "provider routing overhead",
          evidence_paths: [
            "build/provider_routing_overhead_benchmark.json",
            "benchmarks/provider_routing_overhead_benchmark.py",
            "tests/test_provider_routing_overhead_benchmark.py",
          ],
        },
        {
          code: "B6",
          description: "checkpoint and replay overhead",
          evidence_paths: [],
        },
      ],
      required_metrics: ["p50"],
      baselines: ["Algenta Mojo-native path"],
    },
    slo_budgets: [
      {
        name: "runtime_manifest_load",
        applies_to: "first-party runtime manifest route",
        p95_objective_ms: 25,
        hard_ceiling_ms: 100,
      },
      {
        name: "replay",
        applies_to: "runs up to 1000 events",
        p95_objective_ms: 750,
        hard_ceiling_ms: 2000,
      },
    ],
    scheduler_model: {
      policies: ["FIFO"],
      minimize: ["tail latency"],
      maximize: ["GPU or CPU utilization"],
      invariants: ["No request starves indefinitely."],
    },
    memory_model: {
      regions: ["model weights"],
      rules: ["KV pages are tenant-scoped."],
      failure_codes: ["kv_cache_exhausted"],
    },
    evaluation_science: {
      dimensions: ["answer correctness"],
      methods: ["bootstrap confidence intervals"],
      release_blockers: ["replay success regression"],
    },
    typed_failures: [{ code: "replay_mismatch", description: "Replay diverged." }],
    threat_model: {
      threat_classes: ["prompt injection"],
      controls: ["tool allowlists"],
      non_negotiable_rules: ["MCP tools are untrusted by default."],
    },
    formal_release_theorem: {
      statement:
        "A release is valid iff every advertised capability is manifest-listed, proof-backed, policy-covered, replay-tested, and deployment-mode validated.",
      required_conditions: [
        "manifest-listed",
        "proof-backed",
        "policy-covered",
        "replay-tested",
        "deployment-mode validated",
      ],
    },
    release_artifact_bundle: { required_artifacts: ["signed runtime manifest"] },
    release_gates: [{ gate: "A", description: "contract-tested" }],
    immediate_implementation_sequence: [
      { pr: "PR 0", focus: "Runtime truth manifest", deliverables: ["signed manifest"] },
    ],
    manifest_digest: "c".repeat(64),
    signature: {
      algorithm: "hmac-sha256",
      key_id: "runtime-manifest-signing-v1",
      digest_hex: "c".repeat(64),
      signature_hex: "d".repeat(64),
      scope: "control_plane_hmac_v1",
    },
  };
}

export function makeRuntimeAdminModulesPayload(): Record<string, unknown> {
  return {
    runtime_version: "2026.05.0",
    llm_core_manifest: "llm-core-v1",
    module_manifest_version: "runtime-manifest-v1",
    shipping_contract: {
      module_count: 1,
      function_count: 2,
      runtime_core_layer: "mojo_llm_runtime_core",
      benchmark_discovery_rule: SHIPPING_BENCHMARK_DISCOVERY_RULE,
    },
    summary: {
      module_count: 1,
      function_count: 2,
      maturity_counts: { channel_covered: 1 },
      layer_counts: { mojo_llm_runtime_core: 1 },
    },
    proof_matrix: [
      {
        layer: "mojo_llm_runtime_core",
        status: "channel_covered",
        obligations: ["numerical parity"],
        evidence_paths: ["build/proof.json"],
      },
    ],
    modules: [
      {
        name: "bpe_tokenizer",
        capability_id: "mojo_llm_runtime_core.bpe_tokenizer",
        owner: "algenta-runtime-core",
        contract_boundary: "Deterministic Mojo kernel with a bounded manifest-listed surface.",
        function_count: 2,
        functions: ["encode", "decode"],
        layer: "mojo_llm_runtime_core",
        maturity: "channel_covered",
        public_supported_channels: ["python_sdk", "typescript_sdk", "cli", "mcp"],
        validated_auxiliary_channels: ["bundled_worker", "runtime_local"],
        feature_flag_channels: ["http_api_feature_flag"],
        proof_obligations: ["numerical parity"],
        proof_artifacts: ["build/proof.json"],
        promotion_status: "shipping",
        rollback_flag: "runtime.manifest.module.bpe_tokenizer.rollback_to_python",
        benchmark_report_ref: "build/bench.json",
        parity_report_ref: "build/llm_rollout_parity_benchmark.json",
        schema_compat_report_ref: "tests/test_runtime_schema_surface.py",
        isolation_proof_ref: "tests/test_runtime_manifest.py",
        replay_proof_ref: "tests/test_runtime_release_validation.py",
        benchmark_artifact: "build/bench.json",
        benchmark_speedup_x: 101.0,
        compiled_artifact: "mojo_build/bpe_tokenizer",
        compiled_engine: "mojo",
        max_cold_ms: 12.0,
        max_warm_ms: 4.0,
        max_hot_ms: 2.0,
      },
    ],
    manifest_digest: "c".repeat(64),
    signature: {
      algorithm: "hmac-sha256",
      key_id: "runtime-manifest-signing-v1",
      digest_hex: "c".repeat(64),
      signature_hex: "d".repeat(64),
      scope: "control_plane_hmac_v1",
    },
  };
}

export function makeRuntimeAdminBenchmarksPayload(): Record<string, unknown> {
  return {
    runtime_version: "2026.05.0",
    llm_core_manifest: "llm-core-v1",
    module_manifest_version: "runtime-manifest-v1",
    benchmark_discovery_lane: makeBenchmarkDiscoveryLanePayload(),
    benchmarking: {
      classes: [
        {
          code: "B8",
          description: "provider routing overhead",
          evidence_paths: [
            "build/provider_routing_overhead_benchmark.json",
            "benchmarks/provider_routing_overhead_benchmark.py",
            "tests/test_provider_routing_overhead_benchmark.py",
          ],
        },
        {
          code: "B6",
          description: "checkpoint and replay overhead",
          evidence_paths: [],
        },
        {
          code: "B7",
          description: "MCP tool latency",
          evidence_paths: [],
        },
        {
          code: "B9",
          description: "RAG retrieval quality and latency",
          evidence_paths: [],
        },
        {
          code: "B10",
          description: "decision workflow completion latency",
          evidence_paths: DECISION_WORKFLOW_BENCHMARK_EVIDENCE,
        },
      ],
      required_metrics: ["p50"],
      baselines: ["Algenta Mojo-native path"],
    },
    slo_budgets: [
      {
        name: "runtime_manifest_load",
        applies_to: "first-party runtime manifest route",
        p95_objective_ms: 25,
        hard_ceiling_ms: 100,
      },
      {
        name: "mcp_call_first_party",
        applies_to: "first-party or internal MCP tools",
        p95_objective_ms: 400,
        hard_ceiling_ms: 1200,
      },
      {
        name: "decision_plan_creation",
        applies_to: "decision runtime plan generation",
        p95_objective_ms: 750,
        hard_ceiling_ms: 2000,
      },
    ],
    quality_gate_benchmark_classes: [
      {
        code: "B6",
        description: "checkpoint and replay overhead",
        evidence_paths: [],
      },
      {
        code: "B7",
        description: "MCP tool latency",
        evidence_paths: [],
      },
      {
        code: "B9",
        description: "RAG retrieval quality and latency",
        evidence_paths: [],
      },
      {
        code: "B10",
        description: "decision workflow completion latency",
        evidence_paths: DECISION_WORKFLOW_BENCHMARK_EVIDENCE,
      },
    ],
    quality_gate_slo_budgets: [
      {
        name: "mcp_call_first_party",
        applies_to: "first-party or internal MCP tools",
        p95_objective_ms: 400,
        hard_ceiling_ms: 1200,
      },
      {
        name: "decision_plan_creation",
        applies_to: "decision runtime plan generation",
        p95_objective_ms: 750,
        hard_ceiling_ms: 2000,
      },
      {
        name: "replay",
        applies_to: "runs up to 1000 events",
        p95_objective_ms: 750,
        hard_ceiling_ms: 2000,
      },
    ],
    evaluation_science: {
      dimensions: [
        "replay success rate",
        "tool-call correctness",
        "retrieval precision and recall",
        "decision outcome delta",
      ],
      methods: ["bootstrap confidence intervals"],
      release_blockers: [
        "replay success regression",
        "tool-call error-rate increase",
        "RAG precision drop",
        "decision-plan validity drop",
      ],
    },
    evaluation_summary: {
      dimension_count: 4,
      method_count: 1,
      release_blocker_count: 4,
      benchmark_class_count: 4,
      slo_budget_count: 3,
      replay_gate_enabled: true,
      tool_call_quality_gate_enabled: true,
      rag_quality_gate_enabled: true,
      decision_quality_gate_enabled: true,
    },
    compiled_artifacts: [
      {
        kind: "compiled_mojo_binary",
        path: "mojo_build/bpe_tokenizer",
        sha256: "e".repeat(64),
        size_bytes: 4096,
      },
    ],
    shipping_runtime_modules: ["bpe_tokenizer"],
    shipping_runtime_function_counts: [2],
    shipping_runtime_benchmark_speedups_x: [101.0],
    shipping_runtime_benchmark_artifacts: ["build/bench.json"],
    shipping_runtime_compiled_artifacts: ["mojo_build/bpe_tokenizer"],
    shipping_runtime_compiled_engines: ["mojo"],
    shipping_runtime_max_cold_ms: [12.0],
    shipping_runtime_max_warm_ms: [4.0],
    shipping_runtime_max_hot_ms: [2.0],
    module_benchmarks: [
      {
        name: "bpe_tokenizer",
        function_count: 2,
        benchmark_artifact: "build/bench.json",
        benchmark_speedup_x: 101.0,
        compiled_artifact: "mojo_build/bpe_tokenizer",
        compiled_engine: "mojo",
        max_cold_ms: 12.0,
        max_warm_ms: 4.0,
        max_hot_ms: 2.0,
      },
    ],
    manifest_digest: "c".repeat(64),
    signature: {
      algorithm: "hmac-sha256",
      key_id: "runtime-manifest-signing-v1",
      digest_hex: "c".repeat(64),
      signature_hex: "d".repeat(64),
      scope: "control_plane_hmac_v1",
    },
  };
}

export function makeRuntimeReleaseValidationPayload(): Record<string, unknown> {
  return {
    runtime_version: "2026.05.0",
    llm_core_manifest: "llm-core-v1",
    module_manifest_version: "runtime-manifest-v1",
    theorem_statement:
      "A release is valid iff every advertised capability is manifest-listed, proof-backed, policy-covered, replay-tested, and deployment-mode validated.",
    valid_release: true,
    conditions: [
      {
        condition: "manifest-listed",
        satisfied: true,
        detail: "all advertised capabilities are signed manifest entries",
        evidence_paths: ["runtime_manifest.modules"],
      },
    ],
    deployment_mode: "saas",
    deployment_mode_raw: "saas",
    manifest_digest: "c".repeat(64),
    signature: {
      algorithm: "hmac-sha256",
      key_id: "runtime-manifest-signing-v1",
      digest_hex: "c".repeat(64),
      signature_hex: "d".repeat(64),
      scope: "control_plane_hmac_v1",
    },
  };
}
